### ISSUE TITLE
2.0.1: REST API queries crash AMPSubscriber

### ISSUE THREAD

**Issue by lkraav** [wp-media/rocket-lazy-load#74]
Traceback and details available at https://sentry.io/share/issue/e80602bf8b88462dba0ebba60ee4dab0/

Example crash URL https://conversionxl.com/wp-json/wp/v2/posts/40765

Copy-paste for GH issue search keywords

```
[09-Jan-2019 16:46:18 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /home/convers/public_html/wp-includes/query.php:28                                                                                   
Stack trace:
#0 /home/convers/public_html/wp-content/plugins/amp/includes/amp-helper-functions.php(264): get_query_var('amp', false)
#1 /home/convers/public_html/wp-content/plugins/rocket-lazy-load/src/Subscriber/ThirdParty/AMPSubscriber.php(41): is_amp_endpoint()                                                                                                          
#2 /home/convers/public_html/wp-content/plugins/rocket-lazy-load/src/Subscriber/ThirdParty/AMPSubscriber.php(23): RocketLazyLoadPlugin\Subscriber\ThirdParty\AMPSubscriber->isAmpEndpoint()                                                  
#3 /home/convers/public_html/wp-content/plugins/rocket-lazy-load/src/EventManagement/EventManager.php(43): RocketLazyLoadPlugin\Subscriber\ThirdParty\AMPSubscriber->getSubscribedEvents()                                                   
#4 /home/convers/public_html/wp-content/plugins/rocket-lazy-load/src/Plugin.php(86): RocketLazyLoadPlugin\EventManagement\EventManager->addSubscriber(Object(RocketLazyLoadPlugin\Subscriber\ThirdParty\AMPSubscriber))                      
#5 /home/convers/public_html/wp-includes/class-wp-hook.php in /home/convers/public_html/wp-includes/query.php on line 28                                                                                                                     
[09-Jan-2019 16:46:18 UTC] PHP Notice:  is_feed was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://codex.wordpress.org/De
bugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in /home/convers/public_html/wp-includes/functions.php on line 4196                                                        
[09-Jan-2019 16:46:18 UTC] PHP Notice:  is_amp_endpoint was called <strong>incorrectly</strong>. is_amp_endpoint() was called before the &#039;parse_query&#039; hook was called. This function will always return &#039;false&#039; before th
e &#039;parse_query&#039; hook is called. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 0.4.2.) in /home/convers/public_html/wp-
includes/functions.php on line 4196
```

**Comment by janvitos** [comment]
I have the exact same problem since installing 2.0.1. Reverting back to 1.4.9.

**Comment by Tabrisrp** [comment]
Yes I created PR #75 to fix that

**Comment by janvitos** [comment]
Version 2.0.2 of plugin works great. Thanks!
